"""Output metadata hygiene (P3-15, P26b-3): every buyer-facing document
carries the firm's metadata, never the generator's — and what a file
carries at the PART level (tracked changes, comment parts, media) is
inspected, reported, and for the firm's own template, refused.

Three jobs, one leaf module (assembly imports nothing new):

- `firm_identity(workspace)` reads `<workspace>/firm.json` — the firm's
  name lives on the work side only (the owner's call, B119 §1c): the
  public mirror ships `config/`, and the name is residue. Unset → a
  BLANK identity, reported as unconfigured, never a refusal.
- `stamp_docx(...)` / `stamp_core_xml(...)` set the core properties on a
  document (python-docx) or on the raw `docProps/core.xml` part (the
  xlsx zip patch). Firm-owned outputs carry the firm as author and
  last-modified-by; a buyer's form written back keeps the buyer's
  author and gains the firm as last-modified-by. Generator strings
  (python-docx's "generated by …") are always stripped.
- `inspect_document(path)` counts revision marks and lists comment and
  media parts, by tag and part name — never text (the run-log rule).
  `refuse_marked_template(path)` is the firm-owned door: a template
  carrying unaccepted tracked changes or a comments part refuses the
  fill by name; the fix is accepting them in Word.

`docProps/app.xml` is left alone: python-docx exposes no API for it and
its values name Word, not the generator (stated limit, B120).
"""

import json
import re
import zipfile
from datetime import datetime, timezone
from pathlib import Path

from engine.contracts import ContractError

FIRM_FILE = "firm.json"
GENERATOR_MARKERS = ("python-docx", "openpyxl", "generated by")

_REVISION_TAGS = ("w:ins", "w:del", "w:rPrChange", "w:pPrChange",
                  "w:moveFrom", "w:moveTo")
_DOCX_COMMENT_PARTS = re.compile(
    r"^word/(comments\w*\.xml|people\.xml|commentsExtended\.xml)$")
_XLSX_COMMENT_PARTS = re.compile(
    r"^xl/(comments\d*\.xml|threadedComments/.*|persons/.*)$")
_MEDIA_PARTS = re.compile(r"^(word|xl)/(media|charts|drawings)/")
_DOCX_TEXT_PARTS = re.compile(r"^word/(document|header\d*|footer\d*)\.xml$")
_CORE = "docProps/core.xml"


def firm_identity(workspace: Path) -> dict:
    """{"name": str, "company": str, "configured": bool} from
    <workspace>/firm.json; blank and unconfigured when absent or empty."""
    path = Path(workspace) / FIRM_FILE
    if not path.is_file():
        return {"name": "", "company": "", "configured": False}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        raise ContractError(f"{path} is not readable JSON: {exc}") from exc
    if not isinstance(data, dict):
        raise ContractError(f"{path} must hold an object with a name")
    name = str(data.get("name") or "").strip()
    company = str(data.get("company") or name).strip()
    return {"name": name, "company": company, "configured": bool(name)}


def _at(at: str) -> datetime:
    text = at.replace("Z", "+00:00")
    stamp = datetime.fromisoformat(text)
    if stamp.tzinfo is None:
        stamp = stamp.replace(tzinfo=timezone.utc)
    return stamp


def _strip_generator(text: str | None) -> str:
    text = text or ""
    return "" if any(m in text.lower() for m in GENERATOR_MARKERS) else text


def stamp_docx(doc, *, firm: dict, at: str, title: str,
               owned_by_firm: bool) -> None:
    """Set the core properties a python-docx Document carries. Firm-owned:
    author and last-modified-by are the firm, the descriptive fields
    cleared. Buyer-owned: the buyer's author and creation date stand;
    the firm is the last modifier."""
    props = doc.core_properties
    stamp = _at(at)
    if owned_by_firm:
        props.author = firm["name"]
        props.title = title
        props.subject = ""
        props.keywords = ""
        props.category = ""
        props.comments = ""
        props.revision = 1
        props.created = stamp
    else:
        props.author = _strip_generator(props.author)
        props.comments = _strip_generator(props.comments)
    props.last_modified_by = firm["name"]
    props.modified = stamp
    props.content_status = ""


_CORE_NS = {
    "cp": "http://schemas.openxmlformats.org/package/2006/metadata/core-properties",
    "dc": "http://purl.org/dc/elements/1.1/",
    "dcterms": "http://purl.org/dc/terms/",
    "xsi": "http://www.w3.org/2001/XMLSchema-instance",
}


def stamp_core_xml(core_xml: bytes, *, firm: dict, at: str) -> bytes:
    """The buyer-owned rule on a raw docProps/core.xml part (the xlsx
    zip patch): creator kept unless it names a generator, the firm as
    lastModifiedBy, modified = at, description stripped of generators."""
    from lxml import etree

    root = etree.fromstring(core_xml)

    def node(tag):
        prefix, local = tag.split(":")
        found = root.find(f"{{{_CORE_NS[prefix]}}}{local}")
        if found is None:
            found = etree.SubElement(root, f"{{{_CORE_NS[prefix]}}}{local}")
        return found

    creator = node("dc:creator")
    creator.text = _strip_generator(creator.text)
    description = node("dc:description")
    description.text = _strip_generator(description.text)
    node("cp:lastModifiedBy").text = firm["name"]
    modified = node("dcterms:modified")
    modified.text = _at(at).astimezone(timezone.utc).strftime(
        "%Y-%m-%dT%H:%M:%SZ")
    modified.set(f"{{{_CORE_NS['xsi']}}}type", "dcterms:W3CDTF")
    return etree.tostring(root, xml_declaration=True, encoding="UTF-8",
                          standalone=True)


def _core_fields(zf: zipfile.ZipFile) -> dict:
    if _CORE not in zf.namelist():
        return {"creator": "", "last_modified_by": "", "description": ""}
    from lxml import etree

    root = etree.fromstring(zf.read(_CORE))

    def text(tag):
        prefix, local = tag.split(":")
        found = root.find(f"{{{_CORE_NS[prefix]}}}{local}")
        return (found.text or "") if found is not None else ""

    return {"creator": text("dc:creator"),
            "last_modified_by": text("cp:lastModifiedBy"),
            "description": text("dc:description")}


def inspect_document(path: Path) -> dict:
    """What a docx/xlsx carries at the part level — counts and part
    names only, never text. `generator_strings` names which core fields
    still carry a generator's identity (empty on a hygienic output)."""
    path = Path(path)
    with zipfile.ZipFile(path) as zf:
        names = zf.namelist()
        core = _core_fields(zf)
        marks = {tag: 0 for tag in _REVISION_TAGS}
        for name in names:
            if _DOCX_TEXT_PARTS.match(name):
                xml = zf.read(name).decode("utf-8", "replace")
                for tag in _REVISION_TAGS:
                    marks[tag] += len(re.findall(rf"<{tag}[\s>/]", xml))
    comment_parts = sorted(n for n in names
                           if _DOCX_COMMENT_PARTS.match(n)
                           or _XLSX_COMMENT_PARTS.match(n))
    media_parts = sorted(n for n in names if _MEDIA_PARTS.match(n))
    generator = sorted(field for field, value in core.items()
                       if any(m in value.lower() for m in GENERATOR_MARKERS))
    return {"parts": len(names),
            "creator": core["creator"],
            "last_modified_by": core["last_modified_by"],
            "revision_marks": {k: v for k, v in marks.items() if v},
            "comment_parts": comment_parts,
            "media_parts": media_parts,
            "generator_strings": generator}


def refuse_marked_template(template: Path) -> dict:
    """The firm-owned door: a template carrying unaccepted tracked
    changes or a comments part refuses by name — accept or remove them
    in Word before the fill. Returns the inspection when clean."""
    report = inspect_document(template)
    marks = sum(report["revision_marks"].values())
    if marks or report["comment_parts"]:
        raise ContractError(
            f"the firm template {Path(template).name} carries "
            f"{marks} tracked-change mark(s) "
            f"{dict(report['revision_marks'])} and comment part(s) "
            f"{report['comment_parts']} — accept or remove them in Word "
            "before the fill; neither the working copy nor the buyer copy "
            "is produced from a template that would ship its revision "
            "history (P3-15)")
    return report


def hygiene_entry(path: Path, firm: dict) -> dict:
    """The bundle manifest's per-file hygiene block."""
    report = inspect_document(path)
    return {"creator": report["creator"],
            "last_modified_by": report["last_modified_by"],
            "parts": report["parts"],
            "comment_parts": report["comment_parts"],
            "media_parts": report["media_parts"],
            "revision_marks": report["revision_marks"],
            "generator_strings": report["generator_strings"],
            "firm_identity": ("configured" if firm["configured"]
                              else "unconfigured")}
